H01 for today: Revisiting a lot of what we already know
Going back to the Sparrow size dataset
Centrality and spread:
```{r}
d <- read.table("../../week1/data/SparrowSize.txt", header = TRUE, stringsAsFactors = FALSE)
str(d)
d$Tarsus <- as.numeric(as.character(d$Tarsus))
hist(d$Tarsus, main = "", xlab = "Sparrow tarsus length (mm)", col = "grey")
```

Now changing to density plots and lines for mean and SD:
```{r}
hist(d$Tarsus, main="", xlab="Sparrow tarsus length (mm)", col="grey",prob=TRUE) # this argument tells R to plot density instead of frequency,you can see that on the y-axis
lines(density(d$Tarsus,na.rm=TRUE), lwd = 2)
abline(v = mean(d$Tarsus, na.rm = TRUE), col = "red",lwd = 2)
abline(v = mean(d$Tarsus, na.rm = TRUE)-sd(d$Tarsus, na.rm = TRUE), col = "blue",lwd = 2, lty=5)
abline(v = mean(d$Tarsus, na.rm = TRUE)+sd(d$Tarsus, na.rm = TRUE), col = "blue",lwd = 2, lty=5)
```

Then we need to explicitly test why there are 2 peaks in the density plot, is it male-female difference
```{r}
t.test(d$Tarsus ~ d$Sex)
par(mfrow=c(2,1))
hist(d$Tarsus[d$Sex==1], main="", xlab="Male sparrow tarsus length (mm)", col="grey", prob=TRUE)
lines(density(d$Tarsus[d$Sex==1],na.rm=TRUE), lwd = 2)
abline(v = mean(d$Tarsus[d$Sex==1], na.rm = TRUE), col = "red",lwd = 2)
abline(v = mean(d$Tarsus[d$Sex==1], na.rm = TRUE)-sd(d$Tarsus[d$Sex==1], na.rm = TRUE), col = "blue",lwd = 2, lty=5)
abline(v = mean(d$Tarsus[d$Sex==1], na.rm = TRUE)+sd(d$Tarsus[d$Sex==1], na.rm = TRUE), col = "blue",lwd = 2, lty=5)
hist(d$Tarsus[d$Sex==0], main="", xlab="Female sparrow tarsus length (mm)", col="grey", prob=TRUE)
lines(density(d$Tarsus[d$Sex==0],na.rm=TRUE), lwd = 2)
abline(v = mean(d$Tarsus[d$Sex==0], na.rm = TRUE), col = "red",lwd = 2)
abline(v = mean(d$Tarsus[d$Sex==0], na.rm = TRUE)-sd(d$Tarsus[d$Sex==0], na.rm = TRUE), col = "blue",lwd = 2, lty=5)
abline(v = mean(d$Tarsus[d$Sex==0], na.rm = TRUE)+sd(d$Tarsus[d$Sex==0], na.rm = TRUE), col = "blue",lwd = 2, lty=5)
dev.off()
```